.PHONY: clean All

All:
	@echo "----------Building project:[ Aviao - Debug ]----------"
	@cd "Aviao" && $(MAKE) -f  "Aviao.mk"
clean:
	@echo "----------Cleaning project:[ Aviao - Debug ]----------"
	@cd "Aviao" && $(MAKE) -f  "Aviao.mk" clean
